creating a PyTorch tensor as an array

In [2]:
import torch  
arr = [[3, 4], [8, 5]]   
pyTensor = torch.Tensor(arr)  
print(pyTensor)  

tensor([[3., 4.],
        [8., 5.]])


creating a tensor from numpy array

In [3]:
import torch  
import numpy as np1  
numpy_arr = np1.ones((2, 2))  
pyTensor = torch.from_numpy(numpy_arr)  
np1_arr_from_Tensor = pyTensor.numpy()  
print(np1_arr_from_Tensor)  

[[1. 1.]
 [1. 1.]]


PyTorch array

In [5]:
import torch
array = [[1,2,3],[4,5,6]]
tensor = torch.Tensor(array)
print("Array Type: {}".format(tensor.type)) # type
print("Array Shape: {}".format(tensor.shape)) # shape
print(tensor)

Array Type: <built-in method type of Tensor object at 0x000001753D95E670>
Array Shape: torch.Size([2, 3])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
